import type { BookingRecord } from './booking';

const now = '2026-09-02T18:00:00.000Z';

function demo(partial: BookingRecord): BookingRecord {
  return {
    ...partial,
    internalNotes: partial.internalNotes || 'DEMO booking for Studio walkthrough.',
    stripePaymentIntentId: partial.stripePaymentIntentId || '',
    amountRefunded: partial.amountRefunded || 0,
  };
}

export const DEMO_BOOKINGS: BookingRecord[] = [
  demo({
    bookingRef: 'CC-DEMO01',
    createdAt: '2026-08-18T09:12:00.000Z',
    updatedAt: now,
    customerName: 'Alex Campbell',
    customerEmail: 'alex.campbell@example.com',
    customerPhone: '+44 7700 900123',
    customerAddress: '14 Highland Way, Edinburgh, EH1 2NG',
    campsiteLocation: 'Cobleland Campsite, Aberfoyle — Pitch 14',
    specialRequests: 'Arriving around 4pm after hillwalking. One guest is vegetarian.',
    internalNotes: 'DEMO — Deluxe pitch. Balance still outstanding.',
    logistics: {
      pitchDetail: 'Pitch 14, riverbank row, left of the shower block',
      pitchW3w: '',
      accessNotes: 'Site track is single-file after the barrier. Park on the pitch, not the turning circle.',
    },
    checkinDate: '2026-09-12',
    checkoutDate: '2026-09-15',
    nights: 3,
    guests: 4,
    tentType: '5M Bell Tent',
    beddingTier: 'Bedding: Cosy Camping Luxury',
    beddingPrice: 140,
    addons: [
      { title: 'Cosy Kitchen Setup', price: 60 },
      { title: 'Cosy Living Lounge', price: 65 },
      { title: 'Indoor Wood Burner', price: 40 },
      { title: 'Indoor & Outdoor Chairs', price: 40 },
    ],
    fulfillment: 'Cosy Camping Deluxe Setup & Pitching',
    fulfillmentPrice: 225,
    totalRentalPrice: 705.75,
    depositPercent: 50,
    depositAmount: 352.88,
    securityDeposit: 200,
    totalPaidToday: 552.88,
    remainingBalance: 352.87,
    balanceDueDate: '15 Aug 2026',
    amountRefunded: 0,
    stripeSessionId: 'cs_demo_deluxe',
    stripePaymentIntentId: '',
    emails: {
      confirmationAt: '2026-08-18T09:13:00.000Z',
      welcomePackAt: '2026-08-18T09:13:00.000Z',
    },
  }),
  demo({
    bookingRef: 'CC-DEMO02',
    createdAt: '2026-08-10T14:40:00.000Z',
    updatedAt: now,
    customerName: 'Fraser MacLeod',
    customerEmail: 'fraser.macleod@example.com',
    customerPhone: '+44 7700 900456',
    customerAddress: '8 Saltmarket, Glasgow, G1 5LE',
    campsiteLocation: 'Fidden Farm, Isle of Mull',
    specialRequests: 'Collecting Friday 10am from the Falkirk container if possible.',
    internalNotes: 'DEMO — DIY depot pickup, paid in full.',
    checkinDate: '2026-09-18',
    checkoutDate: '2026-09-22',
    nights: 4,
    guests: 2,
    tentType: '4M Bell Tent',
    beddingTier: 'DIY Sleeping (No Bedding)',
    beddingPrice: 0,
    addons: [{ title: 'Fire Cooking Gear', price: 25 }],
    fulfillment: 'DIY Depot Pickup',
    fulfillmentPrice: 0,
    totalRentalPrice: 205,
    depositPercent: 100,
    depositAmount: 205,
    securityDeposit: 200,
    totalPaidToday: 405,
    remainingBalance: 0,
    balanceDueDate: '',
    amountRefunded: 0,
    stripeSessionId: 'cs_demo_diy',
    stripePaymentIntentId: '',
    emails: {
      confirmationAt: '2026-08-10T14:41:00.000Z',
      welcomePackAt: '2026-08-10T14:41:00.000Z',
      diyGuideAt: '2026-08-10T14:41:00.000Z',
    },
  }),
  demo({
    bookingRef: 'CC-DEMO03',
    createdAt: '2026-08-22T11:05:00.000Z',
    updatedAt: now,
    customerName: 'Priya Shah',
    customerEmail: 'priya.shah@example.com',
    customerPhone: '+44 7700 900789',
    customerAddress: '22 Queen Street, Perth, PH2 8BB',
    campsiteLocation: 'Resipole Farm, Ardnamurchan — Pitch 3',
    specialRequests: 'Family of eight. Would like the awning facing the loch if the pitch allows.',
    internalNotes: 'DEMO — Big deluxe family stay, paid in full. Heavy load sheet.',
    checkinDate: '2026-10-02',
    checkoutDate: '2026-10-06',
    nights: 4,
    guests: 8,
    tentType: '6M Cathedral',
    beddingTier: 'Bedding: Cosy Camping Luxury',
    beddingPrice: 280,
    addons: [
      { title: 'Cosy Kitchen Setup', price: 80 },
      { title: 'Cosy Living Lounge', price: 65 },
      { title: 'Indoor Wood Burner', price: 40 },
      { title: 'Outdoor Awning Porch', price: 30 },
      { title: 'Indoor & Outdoor Chairs', price: 80 },
      { title: 'Starlink Satellite Wi-Fi', price: 40 },
    ],
    fulfillment: 'Cosy Camping Deluxe Setup & Pitching',
    fulfillmentPrice: 225,
    totalRentalPrice: 1040,
    depositPercent: 50,
    depositAmount: 520,
    securityDeposit: 200,
    totalPaidToday: 1240,
    remainingBalance: 0,
    balanceDueDate: '',
    amountRefunded: 0,
    stripeSessionId: 'cs_demo_family',
    stripePaymentIntentId: '',
    emails: {
      confirmationAt: '2026-08-22T11:06:00.000Z',
      welcomePackAt: '2026-08-22T11:06:00.000Z',
      balanceReminderAt: '2026-09-01T09:00:00.000Z',
    },
  }),
  demo({
    bookingRef: 'CC-DEMO04',
    createdAt: '2026-08-28T16:20:00.000Z',
    updatedAt: now,
    customerName: 'Jamie and Eilidh Ross',
    customerEmail: 'ross.family@example.com',
    customerPhone: '+44 7700 900321',
    customerAddress: '9 Harbour Road, North Berwick, EH39 4AF',
    campsiteLocation: 'Yellowcraig Beach, East Lothian — Camper pitch near dunes',
    specialRequests: 'Two children (6 and 9). Beach kit for sandy pitch please.',
    internalNotes: 'DEMO — Coastal deluxe with beach kit. Balance due.',
    checkinDate: '2026-09-26',
    checkoutDate: '2026-09-28',
    nights: 2,
    guests: 5,
    tentType: '5M Bell Tent',
    beddingTier: 'Bedding: Essentials',
    beddingPrice: 125,
    addons: [
      { title: 'Indoor & Outdoor Chairs', price: 50 },
      { title: 'Beach & Adventure Kit', price: 20 },
      { title: 'Starlink Satellite Wi-Fi', price: 20 },
    ],
    fulfillment: 'Cosy Camping Deluxe Setup & Pitching',
    fulfillmentPrice: 225,
    totalRentalPrice: 570,
    depositPercent: 50,
    depositAmount: 285,
    securityDeposit: 200,
    totalPaidToday: 485,
    remainingBalance: 285,
    balanceDueDate: '29 Aug 2026',
    amountRefunded: 0,
    stripeSessionId: 'cs_demo_beach',
    stripePaymentIntentId: '',
    emails: {
      confirmationAt: '2026-08-28T16:21:00.000Z',
      welcomePackAt: '2026-08-28T16:21:00.000Z',
    },
  }),
  demo({
    bookingRef: 'CC-DEMO05',
    createdAt: '2026-08-05T08:55:00.000Z',
    updatedAt: now,
    customerName: 'Moira Bennett',
    customerEmail: 'moira.bennett@example.com',
    customerPhone: '+44 7700 900654',
    customerAddress: '3 Castle Terrace, Stirling, FK8 2ED',
    campsiteLocation: 'Red Squirrel Campsite, Glencoe',
    specialRequests: 'First time pitching. Happy to collect Thursday evening from the Falkirk container.',
    internalNotes: 'DEMO — DIY with kitchen + wood burner. Paid in full.',
    checkinDate: '2026-10-09',
    checkoutDate: '2026-10-12',
    nights: 3,
    guests: 3,
    tentType: '4M Bell Tent',
    beddingTier: 'Bedding: Cosy Camping Luxury',
    beddingPrice: 105,
    addons: [
      { title: 'Cosy Kitchen Setup', price: 55 },
      { title: 'Indoor Wood Burner', price: 40 },
    ],
    fulfillment: 'DIY Depot Pickup',
    fulfillmentPrice: 0,
    totalRentalPrice: 300,
    depositPercent: 100,
    depositAmount: 300,
    securityDeposit: 200,
    totalPaidToday: 500,
    remainingBalance: 0,
    balanceDueDate: '',
    amountRefunded: 0,
    stripeSessionId: 'cs_demo_glencoe',
    stripePaymentIntentId: '',
    emails: {
      confirmationAt: '2026-08-05T08:56:00.000Z',
      welcomePackAt: '2026-08-05T08:56:00.000Z',
      diyGuideAt: '2026-08-05T08:56:00.000Z',
    },
  }),
];
